### ISSUE TITLE
Products with Variants

### ISSUE THREAD

**Issue by Dororo02** [boxblinkracer/shopware-ai-demodata#5]
It would be nice if there would be a feature to generate products with variants (for example T-Shirts with different colors and sizes). Currently they would be generated as independent products.

**Comment by boxblinkracer** [comment]
hi there

yep good idea

do you have any idea how you would use it? a special argument like "--variants=true" or how would you tell AI to create variants based on colors for instance?

**Comment by boxblinkracer** [comment]
released with 1.5.0
